# Generated by Django 4.2 on 2024-11-23 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presupuesto', '0001_initial'),
        ('gerencia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cuenta', '0001_initial'),
        ('mes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.SmallIntegerField(default=1, verbose_name='Estado')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuenta.cuenta', verbose_name='Cuenta')),
                ('gerencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gerencia.gerencia', verbose_name='Gerencia')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuesto.presupuesto', verbose_name='Presupuesto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Movimientos de Cuentas',
            },
        ),
        migrations.CreateModel(
            name='DetalleMovimientoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200, verbose_name='Concepto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mes.mes', verbose_name='Mes')),
                ('movimientoCuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalleMovimientoCuenta', to='movimientoscuenta.movimientocuenta')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Movimientos Cuentas',
            },
        ),
    ]
