# Generated by Django 4.2 on 2024-11-26 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimientoscuenta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallemovimientocuenta',
            name='movimientoCuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detallesmc', to='movimientoscuenta.movimientocuenta'),
        ),
    ]
