# Generated by Django 4.2 on 2024-11-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientoscuenta', '0003_rename_movimientocuenta_detallemovimientocuenta_movimientocuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallemovimientocuenta',
            name='estado',
            field=models.SmallIntegerField(default=1, verbose_name='Estado'),
        ),
    ]
