# Generated by Django 5.1.1 on 2024-09-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, unique=True, verbose_name='Codigo')),
                ('cedula', models.CharField(max_length=50, verbose_name='Cedula')),
                ('nombreCompleto', models.CharField(max_length=50, verbose_name='Nombre Completo')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo')),
                ('telefono', models.CharField(max_length=50, verbose_name='Telefono')),
                ('activo', models.PositiveSmallIntegerField(default=1, verbose_name='Activo')),
                ('estado', models.PositiveSmallIntegerField(default=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name_plural': 'Responsables',
            },
        ),
    ]
