# Generated by Django 5.1.1 on 2024-09-24 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipoMovimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroCuenta', models.CharField(max_length=50, unique=True, verbose_name='Numero de Cuenta')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('activo', models.SmallIntegerField(default=1, verbose_name='Activo')),
                ('estado', models.SmallIntegerField(default=1, verbose_name='Estado')),
                ('tipoMovimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipoMovimiento.tipomovimiento', verbose_name='Tipo de Movimiento')),
            ],
            options={
                'verbose_name_plural': 'Cuentas',
            },
        ),
    ]
