# Generated by Django 5.1.1 on 2024-09-24 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Codigo')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('fechaInicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fechaFin', models.DateField(verbose_name='Fecha Fin')),
                ('activo', models.SmallIntegerField(default=1, verbose_name='Activo')),
                ('estado', models.SmallIntegerField(default=1, verbose_name='Estado')),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anio.anio', verbose_name='Anio')),
            ],
            options={
                'verbose_name_plural': 'Presupuestos',
            },
        ),
    ]
