# Generated by Django 4.2 on 2024-11-23 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presupuesto', '0001_initial'),
        ('gerencia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cuenta', '0001_initial'),
        ('mes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjecucionPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.SmallIntegerField(default=1, verbose_name='Estado')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuenta.cuenta', verbose_name='Cuenta')),
                ('gerencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gerencia.gerencia', verbose_name='Gerencia')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuesto.presupuesto', verbose_name='Presupuesto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Ejecuciones de Presupuesto',
            },
        ),
        migrations.CreateModel(
            name='DetalleEjecucionPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montoReal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto real')),
                ('justificacion', models.CharField(max_length=300, verbose_name='Justificacion')),
                ('ejecucionPresupuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ejecucionpresupuesto.ejecucionpresupuesto', verbose_name='EjecucionPresupuesto')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mes.mes', verbose_name='Mes')),
            ],
            options={
                'verbose_name_plural': 'Detalles de EjecucionPresupuesto',
            },
        ),
    ]
