# Generated by Django 4.2 on 2024-11-23 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejecucionpresupuesto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleejecucionpresupuesto',
            name='ejecucionPresupuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalleEjecucionPresupuesto', to='ejecucionpresupuesto.ejecucionpresupuesto'),
        ),
    ]
