# Generated by Django 4.2 on 2024-11-26 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejecucionpresupuesto', '0003_alter_detalleejecucionpresupuesto_ejecucionpresupuesto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleejecucionpresupuesto',
            old_name='ejecucionPresupuesto',
            new_name='ejecucionpresupuesto',
        ),
    ]
