# Generated by Django 4.2 on 2024-11-26 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejecucionpresupuesto', '0004_rename_ejecucionpresupuesto_detalleejecucionpresupuesto_ejecucionpresupuesto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleejecucionpresupuesto',
            old_name='montoReal',
            new_name='montoreal',
        ),
    ]
