# Generated by Django 4.2 on 2024-11-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejecucionpresupuesto', '0005_rename_montoreal_detalleejecucionpresupuesto_montoreal'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleejecucionpresupuesto',
            name='estado',
            field=models.SmallIntegerField(default=1, verbose_name='Estado'),
        ),
    ]
